"""tables environnements, actifs, relations

Revision ID: 3c12fec6128a
Revises: 
Create Date: 2026-10-08 22:12:36.169490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c12fec6128a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environnements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=80), nullable=False),
    sa.Column('est_exemple', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actifs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('environnement_id', sa.Integer(), nullable=False),
    sa.Column('cle', sa.String(length=40), nullable=False),
    sa.Column('nom', sa.String(length=60), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('zone', sa.String(length=40), nullable=False),
    sa.Column('criticite', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.CheckConstraint('criticite BETWEEN 1 AND 5', name='ck_actif_criticite'),
    sa.ForeignKeyConstraint(['environnement_id'], ['environnements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('environnement_id', 'cle', name='uq_actif_cle')
    )
    op.create_table('relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('environnement_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('cible', sa.String(length=40), nullable=False),
    sa.Column('protocole', sa.String(length=60), nullable=False),
    sa.Column('probabilite', sa.Float(), nullable=False),
    sa.Column('mesures', postgresql.ARRAY(sa.String(length=30)), server_default=sa.text("'{}'"), nullable=False),
    sa.CheckConstraint('probabilite BETWEEN 0.01 AND 1', name='ck_relation_probabilite'),
    sa.CheckConstraint('source <> cible', name='ck_relation_pas_de_boucle'),
    sa.ForeignKeyConstraint(['environnement_id', 'cible'], ['actifs.environnement_id', 'actifs.cle'], name='fk_relation_cible', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['environnement_id', 'source'], ['actifs.environnement_id', 'actifs.cle'], name='fk_relation_source', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['environnement_id'], ['environnements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('environnement_id', 'source', 'cible', name='uq_relation_paire')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relations')
    op.drop_table('actifs')
    op.drop_table('environnements')
    # ### end Alembic commands ###
